import { useQuery, gql } from '@apollo/client';

import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

const GET_CLIENTS =gql`
  query ExampleQuery {
  getClients {
    _id
    description
    order
    status
    title
  }
}
`

export default function Home() {
  const { loading, error, data } = useQuery(GET_CLIENTS, {
    onCompleted(data) {
      console.log(data);
    },
  });

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error : {error.message}</p>;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>

        </div>
        <h2>My first Apollo app 🚀</h2>
        <br/>
        <div>
          {data.getClients.map(({ order, description, status, title, _id }: any) => (
              <div key={_id}>
                <h3>{title}</h3>
                <br />
                <b>About this client:</b>
                <p>{description}</p>
                <br />
                <p>Status:</p>
                <p>{status}</p>
                <br />
                <p>Order:</p>
                <h2>{order}</h2>
              </div>
            ))}
        </div>
      </main>
    </>
  )
}
